### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by KoryNunn** [collinskesuibai/eng-dynamics#1]
Hey, I love projects like this that take esoteric maths and make it understandable to developers.

One suggestion I would have before you get too deep into it would be to not shorten identifiers.

eg: 
axlT -> axelTorque?
engT -> engineTorque?

There is nothing to be gained by shortening identifiers, and only understandability to be lost.

I'm very interested to see more functions be implemented!

**Comment by collinskesuibai** [comment]
Hello Kory, the suggestion you made is brilliant and a new commit has been made with the specific requested changes. Thank you for loving the project, the project is open for more suggestions if you have any.
